name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t hello-world:${{ github.sha }} .

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Tag Docker image
      run: |
        docker tag hello-world:${{ github.sha }} ${{ secrets.ECR_REGISTRY }}/hello-world:${{ github.sha }}

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/hello-world:${{ github.sha }}

    - name: Notify Infra Repository
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/chtamanini7/infra-nimbux/dispatches \
        -d '{"event_type":"image-pushed", "client_payload": {"docker_image_sha": "${{ github.sha }}"}}'
